name: musaneda
version: 1.0.1+7
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  sms_autofill: ^2.3.0
  flutter_advanced_drawer: ^1.3.2
  carousel_slider: ^4.1.1
  flutter_svg: ^2.0.7
  get_storage: ^2.0.3
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  location: ^4.4.0
  flutter_easyloading: ^3.0.5
  file_picker: ^5.2.0+1
  uuid: ^3.0.6
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  lazy_load_scrollview: ^1.3.0
  http: ^1.0.0
  connectivity_plus: ^4.0.1
  sqflite: ^2.2.3
  path: ^1.8.2
  mockito: ^5.4.2
  flutter_pdfview: ^1.2.9
  web_socket_channel: ^2.1.0
  socket_io_client: ^2.0.2
  talker: ^3.0.0+1
  photo_view: ^0.14.0
  package_info_plus: ^4.0.2
  flutter_bloc: ^8.1.3
  logger: ^1.3.0
  geocoding: ^2.1.0
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.0.0
  flutter_local_notifications: ^15.0.0
  sentry_flutter: ^7.9.0
  hive: ^2.2.3
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  tamara_sdk: ^0.9.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  integration_test:
    sdk: flutter


flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/drawer/
    - assets/images/services/
    - assets/images/bar/
    - assets/images/png/
    - assets/images/icon/
    - assets/certificate/
    - assets/images/packages/
    - shorebird.yaml

  fonts:
    - family:  mikhak_medium
      fonts:
        - asset: assets/fonts/mikhak_medium.ttf

    - family:  montserrat_black
      fonts:
        - asset: assets/fonts/montserrat_black.ttf

    - family:  montserrat_bold
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf

    - family:  montserrat_extra_light
      fonts:
        - asset: assets/fonts/montserrat_extra_light.ttf

    - family:  montserrat_light
      fonts:
        - asset: assets/fonts/montserrat_light.ttf

    - family:  montserrat_medium
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf

    - family: montserrat_regular
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf

    - family:  montserrat_extra_bold
      fonts:
        - asset: assets/fonts/montserrat_extra_bold.ttf

    - family:  montserrat_semi_bold
      fonts:
        - asset: assets/fonts/montserrat_semi_bold.ttf

    - family:  montserrat_thin
      fonts:
        - asset: assets/fonts/montserrat_thin.ttf